services:
  fivem:
    build:
      context: .
      args:
        CFX_URL: ${CFX_URL}

    image: willem1981/fivem-enhanced:latest

    container_name: fivem-enhanced

    restart: unless-stopped

    stdin_open: true
    tty: true

    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120/tcp"

    volumes:
      - ./server.cfg:/opt/cfx-server-data/server.cfg
      - ./resources:/opt/cfx-server-data/resources

    security_opt:
      - seccomp:unconfined
