services:
  fivem:
    build:
      context: .
      args:
        CFX_URL: ${CFX_URL}
        SERVER_DATA_URL: ${SERVER_DATA_URL}
        SERVER_DATA_BRANCH: ${SERVER_DATA_BRANCH}

    image: willem1981/fivem-enhanced:latest

    container_name: fivem-enhanced

    restart: unless-stopped

    stdin_open: true
    tty: true

    ports:
      - "${HOST_FXSERVER_PORT:-30120}:30120/tcp"
      - "${HOST_FXSERVER_PORT:-30120}:30120/udp"
      - "${HOST_TXADMIN_PORT:-40120}:40120/tcp"

    environment:
      SERVER_DATA_URL: ${SERVER_DATA_URL}
      SERVER_DATA_BRANCH: ${SERVER_DATA_BRANCH}
      SV_LICENSE_KEY: ${SV_LICENSE_KEY}

    security_opt:
      - seccomp:unconfined
